import { Type } from '@fm/di';
export declare const Controller: (this: unknown, ...args: any[]) => (cls: Type<any>) => any;
export declare const Post: (this: unknown, ...args: any[]) => any;
export declare const Get: (this: unknown, ...args: any[]) => any;
export declare const Delete: (this: unknown, ...args: any[]) => any;
export declare const Put: (this: unknown, ...args: any[]) => any;
export declare const All: (this: unknown, ...args: any[]) => any;
export declare const Param: (this: unknown, ...args: any[]) => any;
export declare const Use: (this: unknown, ...args: any[]) => any;
export declare const Options: (this: unknown, ...args: any[]) => any;
