"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Prov = exports.PLATFORM_SCOPE = exports.dyanmicServer = exports.Application = exports.DataError = exports.createInjectableModel = exports.Use = exports.Put = exports.Post = exports.Param = exports.Options = exports.Get = exports.Delete = exports.Controller = exports.All = void 0;
var controller_1 = require("./decorator/controller");
Object.defineProperty(exports, "All", { enumerable: true, get: function () { return controller_1.All; } });
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_1.Controller; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return controller_1.Delete; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return controller_1.Get; } });
Object.defineProperty(exports, "Options", { enumerable: true, get: function () { return controller_1.Options; } });
Object.defineProperty(exports, "Param", { enumerable: true, get: function () { return controller_1.Param; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return controller_1.Post; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return controller_1.Put; } });
Object.defineProperty(exports, "Use", { enumerable: true, get: function () { return controller_1.Use; } });
var sequelize_1 = require("./decorator/sequelize");
Object.defineProperty(exports, "createInjectableModel", { enumerable: true, get: function () { return sequelize_1.createInjectableModel; } });
var data_error_1 = require("./extension/data-error");
Object.defineProperty(exports, "DataError", { enumerable: true, get: function () { return data_error_1.DataError; } });
var platform_1 = require("./providers/platform");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return platform_1.Application; } });
Object.defineProperty(exports, "dyanmicServer", { enumerable: true, get: function () { return platform_1.dyanmicServer; } });
Object.defineProperty(exports, "PLATFORM_SCOPE", { enumerable: true, get: function () { return platform_1.PLATFORM_SCOPE; } });
Object.defineProperty(exports, "Prov", { enumerable: true, get: function () { return platform_1.Prov; } });
