"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dyanmicServer = exports.DataError = exports.createInjectableModel = exports.Options = exports.Use = exports.Param = exports.All = exports.Put = exports.Delete = exports.Get = exports.Post = exports.InjectableRouter = void 0;
var injectable_router_1 = require("./decorator/injectable-router");
Object.defineProperty(exports, "InjectableRouter", { enumerable: true, get: function () { return injectable_router_1.InjectableRouter; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return injectable_router_1.Post; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return injectable_router_1.Get; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return injectable_router_1.Delete; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return injectable_router_1.Put; } });
Object.defineProperty(exports, "All", { enumerable: true, get: function () { return injectable_router_1.All; } });
Object.defineProperty(exports, "Param", { enumerable: true, get: function () { return injectable_router_1.Param; } });
Object.defineProperty(exports, "Use", { enumerable: true, get: function () { return injectable_router_1.Use; } });
Object.defineProperty(exports, "Options", { enumerable: true, get: function () { return injectable_router_1.Options; } });
var sequelize_1 = require("./decorator/sequelize");
Object.defineProperty(exports, "createInjectableModel", { enumerable: true, get: function () { return sequelize_1.createInjectableModel; } });
var data_error_1 = require("./extension/data-error");
Object.defineProperty(exports, "DataError", { enumerable: true, get: function () { return data_error_1.DataError; } });
var platform_1 = require("./providers/platform");
Object.defineProperty(exports, "dyanmicServer", { enumerable: true, get: function () { return platform_1.dyanmicServer; } });
