"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createInjectableModel = exports.Use = exports.Put = exports.Post = exports.Param = exports.Options = exports.Middleware = exports.Get = exports.Delete = exports.Controller = exports.All = exports.FactoryUse = exports.FactoryPut = exports.FactoryPost = exports.FactoryParam = exports.FactoryOptions = exports.FactoryGet = exports.FactoryDelete = exports.FactoryAll = void 0;
// eslint-disable-next-line max-len
var controller_1 = require("./controller");
Object.defineProperty(exports, "FactoryAll", { enumerable: true, get: function () { return controller_1.FactoryAll; } });
Object.defineProperty(exports, "FactoryDelete", { enumerable: true, get: function () { return controller_1.FactoryDelete; } });
Object.defineProperty(exports, "FactoryGet", { enumerable: true, get: function () { return controller_1.FactoryGet; } });
Object.defineProperty(exports, "FactoryOptions", { enumerable: true, get: function () { return controller_1.FactoryOptions; } });
Object.defineProperty(exports, "FactoryParam", { enumerable: true, get: function () { return controller_1.FactoryParam; } });
Object.defineProperty(exports, "FactoryPost", { enumerable: true, get: function () { return controller_1.FactoryPost; } });
Object.defineProperty(exports, "FactoryPut", { enumerable: true, get: function () { return controller_1.FactoryPut; } });
Object.defineProperty(exports, "FactoryUse", { enumerable: true, get: function () { return controller_1.FactoryUse; } });
var controller_2 = require("./controller");
Object.defineProperty(exports, "All", { enumerable: true, get: function () { return controller_2.All; } });
Object.defineProperty(exports, "Controller", { enumerable: true, get: function () { return controller_2.Controller; } });
Object.defineProperty(exports, "Delete", { enumerable: true, get: function () { return controller_2.Delete; } });
Object.defineProperty(exports, "Get", { enumerable: true, get: function () { return controller_2.Get; } });
Object.defineProperty(exports, "Middleware", { enumerable: true, get: function () { return controller_2.Middleware; } });
Object.defineProperty(exports, "Options", { enumerable: true, get: function () { return controller_2.Options; } });
Object.defineProperty(exports, "Param", { enumerable: true, get: function () { return controller_2.Param; } });
Object.defineProperty(exports, "Post", { enumerable: true, get: function () { return controller_2.Post; } });
Object.defineProperty(exports, "Put", { enumerable: true, get: function () { return controller_2.Put; } });
Object.defineProperty(exports, "Use", { enumerable: true, get: function () { return controller_2.Use; } });
var sequelize_1 = require("./sequelize");
Object.defineProperty(exports, "createInjectableModel", { enumerable: true, get: function () { return sequelize_1.createInjectableModel; } });
